export const brand = {
  name: "BREERO",
  headline: "Home services, without the hassle.",
  description: "Book trusted professionals for repairs, maintenance and everyday home services.",
  supportEmail: "support@breero.com",
  colors: {
    primaryBlue: "#146EF5",
    primaryBlueDark: "#0E52C6",
    deepNavy: "#0B1F3A",
    ink: "#10243E",
    teal: "#18B7A0",
    tealDark: "#0F8C7A",
    coral: "#FF6B6B",
    sunYellow: "#FFC857",
    sky: "#EAF4FF",
    mint: "#EAFBF7",
    warmCream: "#FFF8EC",
    lightGray: "#F5F7FA",
    midGray: "#66768A",
    border: "#DCE4EC",
    white: "#FFFFFF",
    success: "#198754",
    warning: "#B66A00",
    error: "#C93838",
  },
  gradients: {
    blue: "linear-gradient(135deg, #146EF5 0%, #0E52C6 100%)",
    blueTeal: "linear-gradient(135deg, #146EF5 0%, #18B7A0 100%)",
    warm: "linear-gradient(135deg, #FFF8EC 0%, #FFFFFF 100%)",
  },
  assets: {
    logoPrimary: "/brand/breero-logo-primary.svg",
    logoWhite: "/brand/breero-logo-white.svg",
    logoDark: "/brand/breero-logo-dark.svg",
    symbolPrimary: "/brand/breero-symbol-primary.svg",
    symbolWhite: "/brand/breero-symbol-white.svg",
    symbolDark: "/brand/breero-symbol-dark.svg",
    wordmarkPrimary: "/brand/breero-wordmark-primary.svg",
    wordmarkWhite: "/brand/breero-wordmark-white.svg",
    wordmarkDark: "/brand/breero-wordmark-dark.svg",
  },
} as const;
